# Generated by Django 3.2.15 on 2022-12-27 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_join_request_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='join_request',
            name='accept',
            field=models.BooleanField(default=False),
        ),
    ]
