# Generated by Django 3.2.15 on 2022-12-27 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_join_request_accept'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_in_month', models.IntegerField(blank=True, null=True)),
                ('shift_time', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
