# Generated by Django 3.2.15 on 2023-01-05 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_cancel_request_repair_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='Error_Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('message', models.TextField()),
            ],
        ),
    ]
