# Generated by Django 3.2.15 on 2023-01-05 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_error_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='error_message',
            name='name',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
