# Generated by Django 3.2.15 on 2023-01-05 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_alter_error_message_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='control_center',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center', models.CharField(max_length=200)),
                ('sought_max', models.IntegerField(blank=True, null=True)),
                ('leader_max', models.IntegerField(blank=True, null=True)),
                ('scout_max', models.IntegerField(blank=True, null=True)),
                ('female_max', models.IntegerField(blank=True, null=True)),
                ('start_res_day', models.IntegerField(blank=True, null=True)),
                ('team_max_amb', models.IntegerField(blank=True, null=True)),
                ('team_max_ob', models.IntegerField(blank=True, null=True)),
                ('count_person_amb', models.IntegerField(blank=True, null=True)),
                ('count_person_ob', models.IntegerField(blank=True, null=True)),
                ('count_person_ob_min', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
