# Generated by Django 3.2.15 on 2023-02-12 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_auto_20230210_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='join_request',
            name='image',
            field=models.ImageField(blank=True, default='/placeholder.png', null=True, upload_to=''),
        ),
    ]
