# Generated by Django 3.2.15 on 2023-02-12 21:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_join_request_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservations_Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center', models.CharField(max_length=200)),
                ('center_want_reserve', models.CharField(max_length=200)),
                ('rank', models.CharField(max_length=200)),
                ('start_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('end_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
