# Generated by Django 3.2.15 on 2023-02-12 22:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_reservations_time_max_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservations_time',
            name='type',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservations_time',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='reservations_time',
            name='max_person',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservations_time',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
